name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'
      - '*/*'
      - '*/*/*'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build, test, and enforce coverage (≥80%)
        run: mvn -B -ntp clean verify

      - name: Upload JaCoCo HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            **/target/site/jacoco/*
            **/target/jacoco*.exec
